name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Dylib
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -shared -framework Foundation FakeBundle.m -o FakeBundle.dylib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FakeBundleDylib
          path: FakeBundle.dylib
